#!/bin/bash

# Get the root directory of the git repository
ROOT_DIR=$(git rev-parse --show-toplevel)

# Run the formatter script
"$ROOT_DIR/formatter.sh"

# Get the list of changed files
changed_files=$(git diff --name-only --cached)

# If there are any changes after formatting, add them to the commit
if [ ! -z "$changed_files" ]; then
    git add $changed_files
fi 