name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: cmake -B build -S . -DBUILD_CPP_ONLY=ON

    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Run tests
      run: |
        # Run all test executables and collect their exit codes
        exit_code=0
        for test in ./build/tests/*; do
          if [ -x "$test" ]; then
            echo "Running $test"
            $test
            test_exit=$?
            if [ $test_exit -ne 0 ]; then
              exit_code=$test_exit
            fi
          fi
        done
        exit $exit_code 